<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Products\Module'                        => __DIR__ . '/Module.php',
    'Products\Controller\SkeletonController' => __DIR__ . '/src/Products/Controller/SkeletonController.php',
    'Products\Framework\TestCase'        => __DIR__ . '/tests/Products/Framework/TestCase.php',
    'Products\SampleTest'                => __DIR__ . '/tests/Products/SampleTest.php',
);