<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Machine\Module'                        => __DIR__ . '/Module.php',
    'Machine\Controller\SkeletonController' => __DIR__ . '/src/Machine/Controller/SkeletonController.php',
    'Machine\Framework\TestCase'        => __DIR__ . '/tests/Machine/Framework/TestCase.php',
    'Machine\SampleTest'                => __DIR__ . '/tests/Machine/SampleTest.php',
);