<?php
$this->HeadScript()->appendFile($basePath . '/js/Datatables/jquery.dataTables.js', 'text/javascript');
$this->HeadScript()->appendFile($basePath . '/js/Machine/list.js', 'text/javascript');

$title = 'Listado de Máquinas';
$this->headTitle($title);
?>

<script type="text/javascript">
    var auxObj = {
        edit_url : "<?= $this->url('home')."Machine/edit/" ?>"
    };
</script>

<section class="work-area">
    <h1><?= $this->escapeHtml($title); ?></h1>
    <a href="<?= $this->url('home')."Machine/add" ?>" class="btn btn-info btn-lg btn-add pull-right"> Agregar Nuevo <span class="icon-plus-3"></span>
    </a>
    <table id="example" class="display table table-striped table-responsive table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Modelo</th>
            <th>Año</th>
            <th>Acciones</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <th>Nombre</th>
            <th>Modelo</th>
            <th>Año</th>
            <th>Acciones</th>
        </tr>
        </tfoot>
    </table>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').dataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "jsonList",
                "dataType": "jsonp"
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        return "<input type='button' class='btn btn-warning' name='editar' onclick=\"javascript:editMachine('"+data+"')\" value='editar'/>"
                    },
                    "targets": 3
                },
            ]
        } );
    } );
</script>