<?php
$this->HeadScript()->appendFile($basePath . '/js/DeadTime/add.js', 'text/javascript');
$title = 'Tiempo Muerto';
$this->headTitle($title);
?>

<section class="work-area">
    <div class="container">

        <h1><?= $this->escapeHtml($title); ?></h1>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('DeadTime', array('action' => 'add')));
        $form->setAttribute('id', 'newDeadTime');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('role', 'form');
        $form->prepare();


        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formHidden($form->get('production_model_id'));
        echo $this->formHidden($form->get('problem'));
        ?>

        <div class="col-md-6">
            <label for="agrupacion">Agrupación:</label>
            <?= $this->formRow($form->get('dead_code_group')); ?><br/>

            <label for="codigo">Código:</label>
            <?= $this->formRow($form->get('death_code_id')); ?><br/>

            <strong>Descripción del Código:</strong> <br/><span id="code_description"></span><br/><br/>

            <div id="sub-group-container">
                <label for="subcodigo">Problema:</label>
                <?= $this->formRow($form->get('death_problem_id')); ?><br/>
            </div>

            <div id="other-problem-container">
                <label for="subcodigo">Otro Problema:</label>
                <?= $this->formRow($form->get('other_problem')); ?><br/>
            </div>
        </div>
        <div class="col-md-6">
            <label for="cmbEstatus">Status Equipo:</label>
            <?= $this->formRow($form->get('machine_status')); ?><br/>

            <?= $this->formRow($form->get('saveBtn')); ?>
        </div>

        <?= $this->form()->closeTag(); ?>

    </div>
</section>
