<?php
$this->HeadScript()->appendFile($basePath . '/js/Datatables/jquery.dataTables.js', 'text/javascript');
$this->HeadScript()->appendFile($basePath . '/js/ProductionModel/StandardProduction/index.js', 'text/javascript');

$title = 'Listado de Producción Estandar';
$this->headTitle($title);
?>

<script type="text/javascript">
    var auxObj = {
        edit_sp_url : "<?= $this->url('home')."StandardProduction/edit/" ?>"
    };
</script>

<section class="work-area">
    <h1><?= $this->escapeHtml($title); ?></h1>
    <a href="<?= $this->url('home')."StandardProduction/add" ?>" class="btn btn-info btn-lg btn-add pull-right"> Agregar Nuevo <span class="icon-plus-3"></span>
    </a>
    <table id="example" class="display table table-striped table-responsive table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Máquina</th>
            <th>Tamaño</th>
            <th>Ciclos x minuto</th>
            <th>Productos x hora</th>
            <th>Runtime</th>
            <th>Personal</th>
            <th>Operaciones</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <th>Máquina</th>
            <th>Tamaño</th>
            <th>Ciclos x minuto</th>
            <th>Productos x hora</th>
            <th>Runtime</th>
            <th>Personal</th>
            <th>Operaciones</th>
        </tr>
        </tfoot>
    </table>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').dataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "StandardProduction/jsonList",
                "dataType": "jsonp"
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        return "<input type='button' class='btn btn-warning' name='editar' onclick=\"javascript:editar('"+data+"')\" value='editar'/>" +
                            "<input type='button' name='remove' class='btn btn-danger' onclick=\"javascript:removeStdProd('"+data+"')\" value='borrar'/>"
                    },
                    "targets": 6
                },
            ]
        } );
    } );
</script>