<?php
$this->HeadScript()->appendFile($basePath . '/js/DeadTime/Work/add.js', 'text/javascript');
$title = 'Agregar Trabajo';
$this->headTitle($title);

?>

<section class="work-area">
    <div class="container">
        <h1>Agregar Trabajo</h1>

        <?php

        $form = $this->form;
        $form->setAttribute('action', $this->url('Work', array('action' => 'add')));
        $form->setAttribute('id', 'tech-work');
        $form->setAttribute('class', 'form-horizontal');
        $form->setAttribute('role', 'form');

        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <div class="row">
            <div class="col-md-6">
                <label for="medida">Fecha:</label><br/>
                <?= $this->formRow($form->get('create_date')); ?><br/><br/>

                <label for="medida">Tipo de Trabajo:</label>
                <?= $this->formRow($form->get('type')); ?><br/>

                <label for="medida">Area:</label>
                <?= $this->formRow($form->get('id_area')); ?><br/>

                <label for="medida">Máquina:</label>
                <?= $this->formRow($form->get('id_machine')); ?><br/>

                <label for="medida">Turno:</label>
                <?= $this->formRow($form->get('id_shift')); ?><br/>

                <label for="medida">Técnico:</label>
                <?= $this->formRow($form->get('id_tech')); ?><br/>


            </div>
            <div class="col-md-6">
                <label for="medida">Crono:</label>
                <?= $this->formRow($form->get('crono')); ?><br/>

                <label for="medida">Total:</label>
                <?= $this->formRow($form->get('total')); ?><br/>


                <label for="medida">Comentarios:</label>
                <?= $this->formRow($form->get('comments')); ?><br/>

                <?= $this->formRow($form->get('saveBtn')); ?>

                <?= $this->formRow($form->get('finishBtn')); ?>
            </div>


            <?= $this->form()->closeTag(); ?>

        </div>
</section>