<?php
$this->HeadScript()->appendFile($basePath . '/css/datatables/jquery.dataTables.css', 'text/css');
$this->HeadScript()->appendFile($basePath . '/css/datatables/demo.css', 'text/css');

$this->HeadScript()->appendFile($basePath . '/js/Datatables/jquery.dataTables.js', 'text/javascript');
$this->HeadScript()->appendFile($basePath . '/js/Products/list.js', 'text/javascript');

$title = 'Listado de Productos';
$this->headTitle($title);
?>

<script type="text/javascript">
    var auxObj = {
        edit_url : "<?= $this->url('home')."Products/edit/" ?>"
    };
</script>

<section class="work-area">
    <h1><?= $this->escapeHtml($title); ?></h1>
    <a href="<?= $this->url('home')."Products/add" ?>" class="btn btn-info btn-lg btn-add pull-right"> Agregar Nuevo <span class="icon-plus-3"></span>
    </a>
    <table id="example" class="display table table-striped table-responsive table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>SKU</th>
            <th>Descripción</th>
            <th>Medida</th>
            <th>Fecha</th>
            <th>Acciones</th>
        </tr>
        </thead>

        <tfoot>
        <tr>
            <th>SKU</th>
            <th>Descripción</th>
            <th>Medida</th>
            <th>Fecha</th>
            <th>Acciones</th>
        </tr>
        </tfoot>
    </table>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').dataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "jsonList",
                "dataType": "jsonp"
            },
            "columnDefs": [
                {
                    // The `data` parameter refers to the data for the cell (defined by the
                    // `data` option, which defaults to the column being worked with, in
                    // this case `data: 0`.
                    "render": function ( data, type, row ) {
                        return "<input type='button' name='editar' class='btn btn-warning' onclick=\"javascript:editProduct('"+row[0]+"')\" value='editar'/>" +
                        "<input type='button' name='remove' class='btn btn-danger' onclick=\"javascript:removeProduct('"+row[0]+"')\" value='borrar'/>"
                    },
                    "targets": 4
                },
            ]
        } );
    } );
</script>