<?php
   // $this->HeadScript()->appendFile($basePath . '/js/Scrap/add.js', 'text/javascript');
    $title = 'Agregar Código Scrap';
    $this->headTitle($title);
?>

<section class="work-area">

    <h1><?= $this->escapeHtml($title); ?></h1>

    <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('ScrapCode', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);

    ?>

    <div class="col-md-6">
        <label for="code">Codigo:</label>
        <?= $this->formRow($form->get('code')); ?><br/>

        <label for="description">Descripcion:</label>
        <?= $this->formRow($form->get('description')); ?><br/>

        <label for="machine_id">machine_id:</label>
        <?= $this->formRow($form->get('machine_id')); ?><br/>

        <?= $this->formRow($form->get('saveBtn')); ?>
    </div>

    <?= $this->form()->closeTag(); ?>

</section>