<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ScrapCode\Module'                        => __DIR__ . '/Module.php',
    'ScrapCode\Controller\SkeletonController' => __DIR__ . '/src/ScrapCode/Controller/SkeletonController.php',
    'ScrapCode\Framework\TestCase'        => __DIR__ . '/tests/ScrapCode/Framework/TestCase.php',
    'ScrapCode\SampleTest'                => __DIR__ . '/tests/ScrapCode/SampleTest.php',
);