<?php
$this->HeadScript()->appendFile($basePath . '/js/Scrap/edit.js', 'text/javascript');
$title = 'Editar Scrap';
$this->headTitle($title);

?>

<section class="work-area">
    <div class="row">
        <div class="container">
            <h1><?= $this->escapeHtml($title); ?></h1>

            <?php

            if ($this->flashMessenger()->hasMessages()) {

                echo '<div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </button>';

                $messages = $this->flashMessenger()->getMessages();
                foreach($messages as $message) {
                    echo $message;
                }

                echo '</div>';
            }

                $form = $this->form;
                $form->setAttribute('action', $this->url(
                    'Scrap',
                    array(
                        'action' => 'edit',
                        'id' => $scrap->id)
                ));
                $form->prepare();


                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('id'));
                echo $this->formHidden($form->get('production_model_id'));
            ?>

            <div class="col-md-6">
                <label for="cmbCodigo">Código:</label>
                <?= $this->formRow($form->get('scrap_code_id')); ?><br/>
                <p><strong>Descripción del código:</strong> <span id="scrap_description"></span></p></br>
            
                <label for="cantidad">Cantidad:</label>
                <?= $this->formRow($form->get('quantity')); ?><br/>
            
                <label for="porcentaje">Porcentaje:</label>
                <span id="lbl_percentage"><?= $scrap->percentage.' %' ?></span>

                <br/><br/>
                <?= $this->formRow($form->get('saveBtn')); ?>
            </div>



            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>