<?php
//Turn on output buffering
ob_start();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>

<style type="text/css">
    body{
        font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
        font-size: 14px;
        line-height: 1.42857143;
        color: #333;
        -webkit-print-color-adjust: exact;
    }

    .main-tbl {
        border: 1px solid #ddd;
    }

    .main-tbl td, .main-tbl th{
        border: 1px solid #ddd;
        padding: 8px;
        line-height: 1.42857143;
        vertical-align: top;
        border-top: 1px solid #ddd;
    }

    .main-tbl th{
        background-color: #f5f5f5;
        padding: 8px;
        line-height: 1.42857143;
        vertical-align: top;
        border-top: 1px solid #ddd;
        text-align: left;
    }

    table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 20px;
        border-spacing: 0;
        border-collapse: collapse;
    }
</style>


<h1>Reporte de Ténicos - Avery</h1>

<h2>
    <?php
    if(!empty($start_date) && !empty($end_date))
        echo "De: $start_date , Hasta: $end_date";
    else
        echo "De: $start_date";
    ?>
</h2>

<table class="main-tbl">
    <tr>
        <th>Técnico</th>
        <th>Turno</th>
        <th>Trabajos (mins)</th>
        <th>Requisiciones (mins)</th>
        <th>Debió Trabajar (mins)</th>
    </tr>

    <?php foreach($techs as $tech): ?>
        <tr>
            <td><?= $tech["usr_name"] ?></td>
            <td><?= $tech["name"] ?></td>
            <td><?= $tech["work_total"] ?></td>
            <td><?= $tech["requisition_total"] ?></td>
            <td><?= $tech["total_minutes"] ?></td>
        </tr>
    <?php endforeach; ?>

</table>

</body>
</html>

<?php
$html_page = ob_get_clean();
$err = "";
$fh = fopen('./public/reports/report.html', 'w') or die("can't open file");
fwrite($fh,'');
fwrite($fh,$html_page);
fclose($fh);

$report_real_path = realpath('.')."/public/reports";

//shell_exec
//shell_exec (Aqui debes cambiar el /usr/local.... por la direccion en donde hayas instalado el exe del wkhtmltopdf
passthru("/usr/local/bin/wkhtmltopdf -O landscape {$report_real_path}/report.html {$report_real_path}/report.pdf",$err);

//Ejemplo
//passthru("C:/wkhtmltopdf/bin/wkhtmltopdf.exe -O landscape {$report_real_path}/report.html {$report_real_path}/report.pdf",$err);

$path = "{$report_real_path}/report.pdf";

// download the file
header("Cache-Control: public");
header("Content-Description: File Transfer");
header("Content-disposition: attachment; filename=tecnicos.pdf");
header("Content-Type: application/pdf");
header("Content-Transfer-Encoding: binary");
header('Content-Length: '. filesize($path));

ob_clean();
flush();

readfile($path);
exit;
?>

