<?php
//$this->headLink()->appendStylesheet($basePath . '/css/datatables/jquery.dataTables.css', 'text/css');
//$this->headLink()->appendStylesheet($basePath . '/css/datatables/demo.css', 'text/css');

$this->HeadScript()->appendFile($basePath . '/js/Datatables/jquery.dataTables.js', 'text/javascript');
$this->HeadScript()->appendFile($basePath . '/js/DeadTime/Requisition/pendings.js', 'text/javascript');

$title = 'Pendientes';
$this->headTitle($title);
?>

<script type="text/javascript">
    var auxObj = {
        edit_url : "<?= $this->url('home')."Requisition/" ?>"
    };
</script>


<section class="work-area">
    <div class="container">

        <h1>Pendientes</h1>

        <div class="row">
            <div class="col-md-12">

                <table class="table table-bordered" style="width:615px;float:right;">
                    <tr>
                        <td>
                            <div>
                                Operaciones
                            </div>
                            <div>
                                <a href="<?= $this->url('home')."Requisition/techs"?>" class="btn btn-success btn-lg btn-add pull-right">
                                    <span class="glyphicon glyphicon-user"></span> Técnicos
                                </a>

                                <a href="<?= $this->url('home')."Work"?>" class="btn btn-warning btn-lg btn-add pull-right">
                                    <span class="glyphicon glyphicon-th-list"></span> Trabajos
                                </a>
                            </div>
                        </td>
                        <td>
                            <div>
                                Reportes
                            </div>
                            <div>
                                <a href="<?= $this->url('home')."Requisition/export"?>" class="btn btn-info btn-lg btn-add pull-right">
                                    <span class="glyphicon glyphicon-download-alt"></span> Pendientes
                                </a>
                                <a href="<?= $this->url('home')."Requisition/exportt"?>" class="btn btn-info btn-lg btn-add pull-right">
                                    <span class="glyphicon glyphicon-download-alt"></span> Técnicos
                                </a>
                            </div>

                        </td>
                    </tr>
                </table>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table id="example" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Hora</th>
                        <th>Req Num.</th>
                        <th>Máquina</th>
                        <th>Técnico</th>
                        <th>Descripción</th>
                        <th>Generó Trabajo</th>
                        <th>Liberada</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Hora</th>
                        <th>Req Num.</th>
                        <th>Máquina</th>
                        <th>Técnico</th>
                        <th>Descripción</th>
                        <th>Generó Trabajo</th>
                        <th>Liberada</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example').dataTable( {
            "processing": true,
            "serverSide": true,
            "order": [ 1, 'desc' ],
            "ajax": {
                "url": "jsonList",
                "dataType": "jsonp"
            },
            "columnDefs": [
                {
                    "render": function ( data, type, row ) {
                        return "<a href=\"javascript:editar('"+data+"')\">"+data+"</a>";
                    },
                    "targets": 1
                },
                {
                    "render": function ( data, type, row ) {
                        if(data < 1)
                            return "<span style='color:red'>No</span>";
                        else
                            return "<span style='color:green'>Si</span>";
                    },
                    "targets": 5
                },
                {
                    "render": function ( data, type, row ) {
                        if(data < 1)
                            return "<span style='color:red'>No</span>";
                        else
                            return "<span style='color:green'>Si</span>";
                    },
                    "targets": 6
                },
            ]
        } );
    } );
</script>